<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>Architect</string>
    <key>scopeName</key>
    <string>source.arc</string>
    <key>firstLineMatch</key>
    <string>^@[a-zA-Z0-9!$%^&amp;*(){}\[\]&lt;&gt;\-_\+=\|\\:;,\.\?/~]+</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#booleans</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#numbers</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#strings</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>pragmas</string>
        <key>name</key>
        <string>entity.name.function.arc</string>
        <key>match</key>
        <string>^@[a-zA-Z0-9!$%^&amp;*(){}\[\]&lt;&gt;\-_\+=\|\\:;,\.\?/~]+</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>map properties (only); map (and vector) names cannot be detected</string>
        <key>begin</key>
        <string>(^[\t ]{2})(?!#)(\S+)(?!\s*#)(?=([\t ]\S+))</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>variable.other.arc</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=$|#)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>$self</string>
          </dict>
        </array>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>comment.line.arc</string>
            <key>match</key>
            <string>#.*$</string>
          </dict>
        </array>
      </dict>
      <key>booleans</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.language.boolean.true.arc</string>
            <key>match</key>
            <string>(?&lt;=\s|^|\G)(true)(?=\s|#|$)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.language.boolean.false.arc</string>
            <key>match</key>
            <string>(?&lt;=\s|^|\G)(false)(?=\s|#|$)</string>
          </dict>
        </array>
      </dict>
      <key>numbers</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.numeric.decimal.arc</string>
            <key>match</key>
            <string>(?&lt;=\s|^|\G)((\d*[.])?\d+)(?=\s|#|$)</string>
          </dict>
        </array>
      </dict>
      <key>strings</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>string.quoted.double.arc</string>
            <key>begin</key>
            <string>(?&lt;=\s|^|\G)(")</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>string.quoted.double.arc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(")</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>string.quoted.double.arc</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>string.quoted.double.arc</string>
                <key>match</key>
                <string>(\\")</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>string.quoted.single.arc</string>
            <key>begin</key>
            <string>(?&lt;=\s|^|\G)(')</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>string.quoted.single.arc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(')</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>string.quoted.single.arc</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>string.quoted.single.arc</string>
                <key>match</key>
                <string>(\\')</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>string.quoted.backtick.arc</string>
            <key>begin</key>
            <string>(?&lt;=\s|^|\G)(`)</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>string.quoted.backtick.arc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(`)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>string.quoted.backtick.arc</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>string.quoted.backtick.arc</string>
                <key>match</key>
                <string>(\\`)</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>string.unquoted.arc</string>
            <key>match</key>
            <string>(?&lt;=\s|^|\G)([a-zA-Z0-9!$%^&amp;*(){}\[\]&lt;&gt;\-_\+=\|\\:;,\.\?/~]+)(?=\s|#|$)</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>
